//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dependency
    {
        public int Id { get; set; }
        public int DependentItem { get; set; }
        public int DependencyItem { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Item Item1 { get; set; }
    }
}
