//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Blobs = new HashSet<Blob>();
            this.Categories = new HashSet<Category>();
            this.Dependencies = new HashSet<Dependency>();
            this.Dependencies1 = new HashSet<Dependency>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public string Type { get; set; }
        public string Address { get; set; }
        public int Version { get; set; }
        public string FriendlyVersion { get; set; }
    
        public virtual ICollection<Blob> Blobs { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<Dependency> Dependencies { get; set; }
        public virtual ICollection<Dependency> Dependencies1 { get; set; }
        public virtual User User { get; set; }
    }
}
